# ME-793 Assignment 2: PCA

In [9]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv("data.csv", delimiter=",")
data_arr = data.values # converting data into a numpy array
data.head()

length  width  thickness
0       7      4          3
1       4      1          8
2       6      3          5
3       8      6          1
4       8      5          7

(a) Write a function for determining PCs of the above dataset X. Standardize your data i.e. use zero mean and normalized data using the ”Standardize” function shown in Tutorial.

In [5]:
def standardize(X):
    mu = sum(X)/len(X)
    var = sum((X-mu)**2)/len(X)
    z = (X-mu)/var**0.5
    return z

In [51]:
def pca(data):
    data_norm = standardize(data)
    A = np.dot(data_norm.transpose(), data_norm) / (data_norm.shape[0]-1)
    w,v = np.linalg.eig(A)
    proj_data = np.matmul(data_norm, v.transpose())
    return v.transpose(), proj_data, w

In [52]:
P, proj_data, eigvals = pca(data_arr)

(b) Show the principal vectors i.e. matrix P.

In [53]:
print(P.shape)
print("Principal vector matrix: ", P)

(3, 3)
Principal vector matrix:  [[-0.64200458 -0.68636164  0.34166917]
 [-0.66321742  0.72074503  0.20166619]
 [ 0.38467229  0.09713033  0.91792861]]


In [56]:
print(len(eigvals))
print("Eigenvalues: ", eigvals)

3
Eigenvalues:  [1.9653046  0.33794439 1.03008435]


(c) Show the transformed data Y.

In [54]:
print(proj_data.shape)
print("Projected Data: ", proj_data)

(10, 3)
Projected Data:  [[-0.56886095  0.11616779 -0.63308837]
 [ 2.81215901  0.28136686 -0.02175664]
 [ 0.60630127  0.1833935  -0.31439935]
 [-2.18616813  0.52943876 -0.81733326]
 [-0.87722291  0.26781044  1.11663456]
 [ 1.18222921 -0.62595722  1.16643533]
 [ 0.7614517   0.58520365 -1.24020751]
 [-1.17684005 -0.17047777  1.69770739]
 [-0.27992753  0.18912391  0.05638228]
 [-0.27312162 -1.35606992 -1.01037444]]


(d) Determine the variances along the principal directions.

In [55]:
for i, val in enumerate(eigvals):
    print("% Variance explained by PC {}: ".format(i+1), val/sum(eigvals))

% Variance explained by PC 1:  0.5895913787011411
% Variance explained by PC 2:  0.10138331566589406
% Variance explained by PC 3:  0.3090253056329648


(e) Determine the principal axes using Scikit learn and compare with your solution. Does your solution compare well with that from the python library functions ? Why or why not ?

In [57]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 3)

In [58]:
data_norm = standardize(data_arr)
pca.fit(data_norm)

PCA(n_components=3)

In [69]:
print(pca.components_) # the eigenvectors (P matrix) calculated

[[-0.64200458 -0.68636164  0.34166917]
 [ 0.38467229  0.09713033  0.91792861]
 [ 0.66321742 -0.72074503 -0.20166619]]


In [67]:
cov_matrix = np.matmul(data_norm.transpose(), data_norm) / (data_norm.shape[0]-1)
eigvals_ = []
for eigenvector in pca.components_:
    eigvals_.append(np.dot(eigenvector.T, np.dot(cov_matrix, eigenvector)))
print("Eigenvalues calculated from sklearn: ", eigvals_)

Eigenvalues calculated from sklearn:  [1.9653045956704716, 1.0300843521098824, 0.3379443855529801]


In [59]:
print(pca.explained_variance_ratio_)

[0.58959138 0.30902531 0.10138332]


The results (explained variance, eigenvalues and P matrix) obtained from scikit learn library are very similar to the ones obtained from the python functions. The order of eigenvectors and hence eigenvalues obtained from the python function is not sorted according to the explained variance but the values are almost same (differing only after 6 decimal places).

(f) Determine the principal axes using numpy and compare with your solution. Does your solution compare well with that from the python library functions? Why or why not?

(g) How many PCs are sufficient to represent the data in reduced dimensions with 95 % accuracy. Show how did you come up with you answer.

In [70]:
print(pca.explained_variance_ratio_)

[0.58959138 0.30902531 0.10138332]


As can be seen above, the variance ratios of the 3 PCs obtained from the given data is arranged in a descending order. In order to represent the data with 95% accuracy, we would need all the 3 PCs because the largest 2 can explain 90% of data but the rest 10% can be represented after including the 3rd PC only.